### ISSUE TITLE
Docker compose. Verify doesn't work because doesn't trust the certificate authority.

### ISSUE THREAD

**Issue by ssveta7ak** [pomerium/verify#101]
Quickstart Pomerium Core using Docker.
https://www.pomerium.com/docs/quickstart

## What happened?
1. Verify doesn't work because doesn't trust the certificate authority.

## How'd it happen?

1. Run docker-compose up;
docker-compose.yaml
```
version: "3"
services:
  pomerium:
    image: pomerium/pomerium:v0.21.0-rc2
    volumes:
      - ./config.yaml:/pomerium/config.yaml:ro
    ports:
      - 443:443
  verify:
    image: pomerium/verify:latest
    expose:
      - 8000
```
config.yaml
```

authenticate_service_url: https://authenticate.localhost.pomerium.io
idp_provider: 'auth0'
idp_provider_url: 'https://dev-zecq6kxx.us.auth0.com'
idp_client_id: <>
idp_client_secret: <>
routes:
  - from: https://verify.localhost.pomerium.io
    to: http://verify:8000
    policy:
      - allow:
          or:
            - email:
                is: user@pomerium.com
    pass_identity_headers: true
```

![Screenshot from 2023-02-03 12-11-55.png](https://images.zenhubusercontent.com/63bc6de617e71f0442fdda1c/6cce6135-88bf-4902-b6a0-71ab7e8bdb08)
