### ISSUE TITLE
"Unsigned Identity Headers" section does not show custom claim headers

### ISSUE THREAD

**Issue by kenjenkins** [pomerium/verify#161]
When I run the `verify` service locally, with a custom JWT claim header configured in Pomerium, I do not see this header in the "Unsigned Identity Headers" section:

<img width="665" alt="Screen Shot 2023-06-05 at 1 21 44 PM" src="https://github.com/pomerium/verify/assets/51246568/0618a210-8665-4c0c-b4a1-7b7519cbfecc">

Relevant Pomerium configuration:

```
jwt_claims_headers:
  X-Pomerium-Claim-Photo: picture

routes:
  - from: https://verify.localhost.pomerium.io
    to: http://localhost:8000
    pass_identity_headers: true
    allow_any_authenticated_user: true
```
