### ISSUE TITLE
Verify App Only Accepts Authenticated JWTs

### ISSUE THREAD

**Issue by alexfornuto** [pomerium/verify#4]
## What happened?
Following our [Quickstart](https://pomerium.com/docs/install/) guide I set up Pomerium and Verify as docker containers. When I when to my verify endpoint, it failed to display any user data.

Setting  a `signing_key` value to be made available in the `well-known` endpoint resolved.

## What did you expect to happen?
I would expect the Verify app to still display user data, perhaps with a caveat that the JWT could not be verified because the signing key was not made public.

## What's your environment like?

- Pomerium container `pomerium/pomerium:latest`
- Verify container `pomerium/verify:latest`

**Comment by calebdoxsey** [comment]
This was fixed but the tag in docker hub hasn't been updated in a year. I think we aren't deploying the docker containers.

**Comment by calebdoxsey** [comment]
This bit is missing:

```yaml
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --config .github/goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPARITOR_GITHUB_TOKEN: ${{ secrets.APPARITOR_GITHUB_TOKEN }}
```

I don't have the credentials, so putting this back into Ready.
